language: c

sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - source devtools/travis-ci/install.sh

script:
  - conda config --add channels https://conda.anaconda.org/omnia
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34

  global:
    # BINSTAR
    - secure: "UGmEljhTf6mQxjhj6We2PPNaNsaYONoFgH30SEofJDNIqXSM6zNQzSVOm5RBxfvVdw+TSYwmyZ/XmMio+yIWMDBXXW8MbGHWYIGqevSkgqCT9qqZv2475MCyPFpmyucQzN+0/3+b7JxAR/VC2N6CLPGohsUe1Up/xU3MfY5DcJY="

after_success:
  - source devtools/travis-ci/post_binstar.sh

