language: python

sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake wget
  # Build GROMACS
  - wget ftp://ftp.gromacs.org/pub/gromacs/gromacs-4.6.7.tar.gz
  - tar xfz gromacs-4.6.7.tar.gz
  - cd gromacs-4.6.7
  - mkdir build
  - cd build
  - cmake .. -DGMX_BUILD_OWN_FFTW=ON -DGMX_DOUBLE=ON
  - make -j 2
  - sudo make install
  - source /usr/local/gromacs/bin/GMXRC
  - cd ../..
  # Build LAMMPS
  - wget http://lammps.sandia.gov/tars/lammps-9Dec14.tar.gz
  - tar xfz lammps-9Dec14.tar.gz
  - cd lammps-9Dec14/src
  - make serial -j 2
  - mkdir $HOME/bin
  - mv lmp_serial $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - cd ../..


install:
  - pip install coverage
  - pip install coveralls
  - pip install pytest
  - pip install -r requirements.txt
  - pip install .

script:
  - coverage run --rcfile=.coveragerc --source=intermol setup.py tests

after_script:
  - coveralls
