package:
  name: intermol-dev
  version: !!str 0.1.0.dev0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - openmm
    - six

test:
  requires:
    - pytest
  commands:
    - py.test --pyargs intermol

about:
  home: http://shirtsgroup.github.io/intermol
  license: MIT
  summary: A conversion tool for molecular dynamics simulation.
